# Generated by Django 6.1 on 2026-08-30 08:39

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('uzum', 'Uzum'), ('paynet', 'Paynet'), ('octo', 'Octo'), ('multicard', 'Multicard')], max_length=32, verbose_name='provider')),
                ('credentials_blob', encrypted_model_fields.fields.EncryptedTextField(blank=True, default='', verbose_name='credentials')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='enabled')),
                ('is_test_mode', models.BooleanField(default=True, help_text="Use the provider's sandbox instead of real money.", verbose_name='test mode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='merchants.sellerprofile', verbose_name='seller')),
            ],
            options={
                'verbose_name': 'provider integration',
                'verbose_name_plural': 'provider integrations',
                'ordering': ('provider',),
                'constraints': [models.UniqueConstraint(fields=('seller', 'provider'), name='unique_seller_provider')],
            },
        ),
    ]
