# Generated by Django 6.1 on 2026-08-30 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, db_index=True, max_length=32, unique=True, verbose_name='reference')),
                ('provider', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('uzum', 'Uzum'), ('paynet', 'Paynet'), ('octo', 'Octo'), ('multicard', 'Multicard')], max_length=32, verbose_name='provider')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='created', max_length=16, verbose_name='status')),
                ('provider_txn_id', models.CharField(blank=True, default='', max_length=255, verbose_name='provider transaction id')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='raw payload')),
                ('is_test_mode', models.BooleanField(default=True, verbose_name='test mode')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='paid at')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='merchants.sellerprofile', verbose_name='seller')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['seller', '-created_at'], name='payments_tr_seller__b86051_idx')],
            },
        ),
    ]
