# Generated by Django 6.1 on 2026-09-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Returned to customer')], db_index=True, default='created', max_length=16, verbose_name='status'),
        ),
    ]
