"""Concatenate the design system into one stylesheet for production.

Seven files is how the CSS stays navigable while it is being written — tokens,
components, nav, layouts, marketing, integrations, reports. Seven requests is
not how it should be served to a phone in a shop.

So the files stay separate in the repo and in development, and this writes
`static/css/bundle.css` for production. `base.html` links the bundle when
DEBUG is off and the seven files when it is on, which means what you edit is
always what you see locally.

    python manage.py bundlecss

Run it before `collectstatic` — the deploy script does, and a test fails if
the bundle on disk is stale relative to its sources.
"""
import pathlib

from django.conf import settings
from django.core.management.base import BaseCommand, CommandError

# Order matters and is the cascade: tokens define the variables everything
# else reads, components before the layouts that arrange them, page-specific
# sheets last so they can override.
SOURCES = [
    "fonts.css",
    "tokens.css",
    "components.css",
    "nav.css",
    "layouts.css",
    "marketing.css",
    "integrations.css",
    "reports.css",
]

BUNDLE = "bundle.css"

HEADER = """/* Generated by `python manage.py bundlecss` - do not edit.

   Source files, in cascade order:
{listing}

   Edit those and re-run the command. base.html serves this only when
   DEBUG is off; in development it links the sources directly. */
"""


def css_dir() -> pathlib.Path:
    return pathlib.Path(settings.BASE_DIR) / "static" / "css"


def sources_newer_than_bundle() -> bool:
    """Is the bundle stale? Used by the command and by the test that guards it."""
    directory = css_dir()
    bundle = directory / BUNDLE
    if not bundle.exists():
        return True
    built = bundle.stat().st_mtime
    return any((directory / name).stat().st_mtime > built for name in SOURCES)


def build() -> tuple[pathlib.Path, int]:
    directory = css_dir()
    missing = [name for name in SOURCES if not (directory / name).exists()]
    if missing:
        raise CommandError(f"missing source stylesheet(s): {', '.join(missing)}")

    listing = "\n".join(f"     {name}" for name in SOURCES)
    parts = [HEADER.format(listing=listing)]
    for name in SOURCES:
        parts.append(f"\n/* ===== {name} ===== */\n")
        text = (directory / name).read_text(encoding="utf-8")
        # The font files are referenced as ../fonts/x.woff2 from css/, and the
        # bundle sits in the same directory, so the relative paths still
        # resolve. Worth stating, because moving the bundle would break them.
        parts.append(text.rstrip() + "\n")

    output = "\n".join(parts)
    target = directory / BUNDLE
    target.write_text(output, encoding="utf-8")
    return target, len(output.encode("utf-8"))


class Command(BaseCommand):
    help = "Concatenate the design-system stylesheets into static/css/bundle.css"

    def handle(self, *args, **options):
        target, size = build()
        self.stdout.write(
            self.style.SUCCESS(
                f"wrote {target.name} from {len(SOURCES)} files, {size // 1024} KB"
            )
        )
