# Generated by Django 6.1 on 2026-08-29 19:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Format: +998 XX XXX XX XX', regex='^\\+998 \\d{2} \\d{3} \\d{2} \\d{2}$')], verbose_name='phone number')),
                ('address', models.CharField(max_length=255, verbose_name='delivery address')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='number of cards')),
                ('comment', models.TextField(blank=True, max_length=1000, verbose_name='comment')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='new', max_length=16, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'card order',
                'verbose_name_plural': 'card orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Format: +998 XX XXX XX XX', regex='^\\+998 \\d{2} \\d{3} \\d{2} \\d{2}$')], verbose_name='phone number')),
                ('message', models.TextField(max_length=2000, verbose_name='message')),
                ('is_handled', models.BooleanField(default=False, verbose_name='handled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'contact message',
                'verbose_name_plural': 'contact messages',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('body', models.CharField(blank=True, max_length=500, verbose_name='text')),
                ('level', models.CharField(choices=[('info', 'Information'), ('success', 'Good news'), ('warning', 'Attention')], default='info', max_length=16, verbose_name='kind')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='link')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='core_notifi_user_id_f286cd_idx')],
            },
        ),
    ]
