# Generated by Django 6.1 on 2026-08-29 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='pay link id')),
                ('business_name', models.CharField(max_length=120, verbose_name='business name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='seller_logos/', verbose_name='logo')),
                ('contact_phone', models.CharField(blank=True, max_length=17, verbose_name='contact phone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('welcome_text', models.CharField(blank=True, max_length=200, verbose_name='welcome text')),
                ('thank_you_text', models.CharField(blank=True, max_length=200, verbose_name='thank-you text')),
                ('min_amount', models.DecimalField(decimal_places=2, default=1000, max_digits=12, verbose_name='minimum amount')),
                ('max_amount', models.DecimalField(decimal_places=2, default=10000000, max_digits=12, verbose_name='maximum amount')),
                ('status', models.CharField(choices=[('pending', 'Awaiting approval'), ('approved', 'Approved'), ('suspended', 'Suspended')], default='pending', max_length=16, verbose_name='status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sellers', to=settings.AUTH_USER_MODEL, verbose_name='approved by')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'seller',
                'verbose_name_plural': 'sellers',
                'ordering': ('-created_at',),
            },
        ),
    ]
