# Generated by Django 6.1 on 2026-08-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=17, verbose_name='phone number')),
                ('purpose', models.CharField(choices=[('register', 'Registration'), ('reset', 'Password reset')], default='register', max_length=16, verbose_name='purpose')),
                ('code_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'phone code',
                'verbose_name_plural': 'phone codes',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['phone', 'purpose', '-created_at'], name='accounts_ph_phone_540ab7_idx')],
            },
        ),
    ]
